apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-zabbix-agent-to-server
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: zabbix-agent
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: zabbix-server
    ports:
    - protocol: TCP
      port: 10050
