server:
  image:
    tag: "5.4.0"
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

frontend:
  service:
    type: ClusterIP

database:
  type: postgresql
  postgresql:
    postgresqlDatabase: zabbix
    postgresqlUsername: zabbix
    postgresqlPassword: zabbixpassword
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

web: 
  env: 
    DB_SERVER_HOST: "zabbix-postgresql.monitoring.svc.cluster.local"
    POSTGRES_DB: "zabbix"
    POSTGRES_USER: "zabbix"
    POSTGRES_PASSWORD: "zabbixpassword"