apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:latest
        ports:
        - containerPort: 10050
          name: zabbix-agent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/zabbix/zabbix_agent2.conf
          subPath: zabbix_agent2.conf
        - name: log-volume
          mountPath: /var/log/zabbix
        - name: run-volume
          mountPath: /var/run/zabbix
      volumes:
      - name: config-volume
        configMap:
          name: zabbix-agent-config
      - name: log-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      securityContext:
        runAsUser: 0
