pipeline {
  agent any
  environment {
    GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp-service-account-key')
  }
  stages {
    stage('Terraform Init & Apply') {
      steps {
        dir('terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }
    stage('Helm Deploy Zabbix') {
      steps {
        dir('helm/zabbix') {
          sh 'helm upgrade --install zabbix zabbix-community/zabbix -f values.yaml --namespace monitoring --create-namespace --dependency-update'
        }
      }
    }
    stage('Helm Deploy Grafana') {
      steps {
        dir('helm/grafana') {
          sh 'helm upgrade --install grafana grafana/grafana -f values.yaml --namespace monitoring'
        }
      }
    }
    stage('Apply k8s Manifests') {
      steps {
        dir('k8s-manifests') {
          sh 'kubectl apply -f namespaces.yaml'
          sh 'kubectl apply -f ingress.yaml'
        }
      }
    }
  }
}
