pipeline {
  agent any
  environment {
    GCP_PROJECT = 'careful-airfoil-470112-u0'
    GCP_ZONE = 'us-central1-a'
    GCP_CLUSTER = 'cluster-zabbix-grafana'
    NAMESPACE = 'monitoring'
    GCLOUD_BIN = '/Users/marcio/Downloads/google-cloud-sdk/bin/gcloud'
  }
  stages {
    stage('Autenticar e Provisionar Infraestrutura') {
      steps {
        withCredentials([file(credentialsId: 'gcp-service-account-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
          sh 'ls -l $GOOGLE_APPLICATION_CREDENTIALS'  // Validar arquivo
          sh '$GCLOUD_BIN auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS'
          dir('terraform') {
            sh 'terraform init'
            sh 'terraform apply -auto-approve'
          }
        }
      }
    }
    stage('Configurar kubectl') {
      steps {
        withCredentials([file(credentialsId: 'gcp-service-account-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
          sh '$GCLOUD_BIN auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS'
          sh '$GCLOUD_BIN container clusters get-credentials $GCP_CLUSTER --zone $GCP_ZONE --project $GCP_PROJECT'
        }
      }
    }
    stage('Criar Namespace') {
      steps {
        sh 'kubectl apply -f k8s-manifests/namespaces.yaml'
      }
    }
    stage('Deploy Zabbix via Helm') {
      steps {
        dir('helm/zabbix') {
          sh 'helm repo add zabbix-community https://zabbix-community.github.io/helm-zabbix'
          sh 'helm repo update'
          sh 'helm upgrade --install zabbix zabbix-community/zabbix -f values.yaml --namespace $NAMESPACE --create-namespace --dependency-update'
        }
      }
    }
    stage('Deploy Grafana via Helm') {
      steps {
        dir('helm/grafana') {
          sh 'helm repo add grafana https://grafana.github.io/helm-charts'
          sh 'helm repo update'
          sh 'helm upgrade --install grafana grafana/grafana -f values.yaml --namespace $NAMESPACE'
        }
      }
    }
    stage('Aplicar Ingress') {
      steps {
        sh 'kubectl apply -f k8s-manifests/ingress.yaml'
      }
    }
  }
}
